version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  project-kakaoapi-redis:                        # 서비스명
    container_name: project-kakaoapi-redis       # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: yuncoding1010/project-kakaoapi-redis
    ports:
      - "6739:6739"
  project-kakaoapi-database:
    container_name: project-kakaoapi-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: yuncoding1010/project-kakaoapi-database
    environment:
      - MARIADB_DATABASE=project-kakaoapi
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
